version: "3.9"
services:
  aas-repository:
    image: "eclipsebasyx/aas-repository:2.0.0-SNAPSHOT"
    ports:
      - "8084:8084"
    networks:
      - backend
  sm-repository:
    image: "eclipsebasyx/submodel-repository:2.0.0-SNAPSHOT"
    ports:
      - "8085:8085"
    networks:
      - backend
  aas2openapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - AAS_SERVER_HOST=host.docker.internal
      - AAS_SERVER_PORT=8084
      - SUBMODEL_SERVER_HOST=host.docker.internal
      - SUBMODEL_SERVER_PORT=8085
    depends_on:
      - aas-repository
      - sm-repository
    networks:
      - backend

networks:
  backend:
    driver: bridge