services:
  aas-repository:
    image: "eclipsebasyx/aas-repository:2.0.0-SNAPSHOT"
    ports:
      - "8081:8081"
  sm-repository:
    image: "eclipsebasyx/submodel-repository:2.0.0-SNAPSHOT"
    ports:
      - "8082:8081"
